const sidebars = {
  electronSidebar: [
    {
      type: 'autogenerated',
      dirName: 'electron',
    },
  ],
  tauriSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tauri',
    },
  ],
  rustSidebar: [
    {
      type: 'autogenerated',
      dirName: 'rust',
    },
  ],
};

module.exports = sidebars;
